// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApBzqow7SGurLA7keyTP0VqkUbpAINMhc',
    appId: '1:63271086726:web:b0722bb77c84a3e64d3f07',
    messagingSenderId: '63271086726',
    projectId: 'crypto-list-app-f0628',
    authDomain: 'crypto-list-app-f0628.firebaseapp.com',
    storageBucket: 'crypto-list-app-f0628.appspot.com',
    measurementId: 'G-0RH9LX7G5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB30gKqlhr7cWVB5maQdPBHv46U0WIt8ZA',
    appId: '1:63271086726:android:94b15a6c97241aea4d3f07',
    messagingSenderId: '63271086726',
    projectId: 'crypto-list-app-f0628',
    storageBucket: 'crypto-list-app-f0628.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeD_1dILnCE1fAy4VDQ9bybCQyWA3CkAI',
    appId: '1:63271086726:ios:43902a177c5154444d3f07',
    messagingSenderId: '63271086726',
    projectId: 'crypto-list-app-f0628',
    storageBucket: 'crypto-list-app-f0628.appspot.com',
    iosBundleId: 'com.example.cryptocurrencyapp.testFlutter2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeD_1dILnCE1fAy4VDQ9bybCQyWA3CkAI',
    appId: '1:63271086726:ios:b0157cef4c5239354d3f07',
    messagingSenderId: '63271086726',
    projectId: 'crypto-list-app-f0628',
    storageBucket: 'crypto-list-app-f0628.appspot.com',
    iosBundleId: 'com.example.cryptocurrencyapp.testFlutter2.RunnerTests',
  );
}
